### ISSUE TITLE
Add support for new bigquery_config fields

### ISSUE THREAD

**Issue by azen1k5** [mineiros-io/terraform-google-pubsub-subscription#11]
Hi,

google added two new fields to the _bigquery_config_ block:

* [use_table_schema](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#use_table_schema) introduced in version [v5.14.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.14.0)
* [service_account_email](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#service_account_email) introduced in version [v5.35.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.35.0)

Could you please add support for them to this module?
Also it would be nice if you updated your topics module after releasing the subscription module.

**Comment by zied-elouaer** [comment]
Done in https://github.com/mineiros-io/terraform-google-pubsub-subscription/pull/13
